package com.wzz.lobotocraft.init;

import com.wzz.lobotocraft.ModMain;
import com.wzz.lobotocraft.item.ego.butterfly_funeral.ButterflyFuneralWeapon;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class ModTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, ModMain.MODID);

	public static final RegistryObject<CreativeModeTab> TAB_LOBOTOCRAFT_ENTITY = REGISTRY.register("tablobotocraft_entity",
			() -> CreativeModeTab.builder().title(Component.translatable("itemGroup.lobotocraft_entity")).icon(() -> new ItemStack(ModItems.ONEBAD_SPAWN_EGG.get())).displayItems((parameters, tabData) -> {
						tabData.accept(ModItems.ONEBAD_SPAWN_EGG.get());
						tabData.accept(ModItems.CLERK_SPAWN_EGG.get());
						tabData.accept(ModItems.HAPPY_TEDDY_SPAWN_EGG.get());
						tabData.accept(ModItems.IRON_MAIDEN_SPAWN_EGG.get());
						tabData.accept(ModItems.MEAT_IDOL_SPAWN_EGG.get());
						tabData.accept(ModItems.ABANDONED_MURDERER_SPAWN_EGG.get());
						tabData.accept(ModItems.LARGE_BIRD_SPAWN_EGG.get());
						tabData.accept(ModItems.PUNISHING_BIRD_SPAWN_EGG.get());
						tabData.accept(ModItems.APPROVAL_BIRD_SPAWN_EGG.get());
						tabData.accept(ModItems.FOURTH_MATCH_FLAME_SPAWN_EGG.get());
						tabData.accept(ModItems.WINGBEAT_SPAWN_EGG.get());
						tabData.accept(ModItems.QUEEN_BEE_SPAWN_EGG.get());
						tabData.accept(ModItems.RED_SHOES_SPAWN_EGG.get());
						tabData.accept(ModItems.SNOWQUEEN_SPAWN_EGG.get());
						tabData.accept(ModItems.PPODAE_SPAWN_EGG.get());
						tabData.accept(ModItems.CHILDREN_GALAXY_SPAWN_EGG.get());
						tabData.accept(ModItems.BLUE_STAR_SPAWN_EGG.get());
						tabData.accept(ModItems.THORN_BUS_SPAWN_EGG.get());
						tabData.accept(ModItems.END_BIRD_SPAWN_EGG.get());
						tabData.accept(ModItems.AMBER_DAWN_SPAWN_EGG.get());
						tabData.accept(ModItems.VIOLET_NOON_SPAWN_EGG.get());
						tabData.accept(ModItems.GREEN_NOON_SPAWN_EGG.get());
						tabData.accept(ModItems.ISHARMLA_SPAWN_EGG.get());
						tabData.accept(ModItems.BUTTERFLY_FUNERAL_SPAWN_EGG.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_SPAWN_EGG.get());
						tabData.accept(ModItems.FRAGMENT_OF_THE_UNIVERSE_SPAWN_EGG.get());
						tabData.accept(ModItems.BIGBADWOLF_SPAWN_EGG.get());
						tabData.accept(ModItems.HELPER_SPAWN_EGG.get());
						tabData.accept(ModItems.SKADI_SPAWN_EGG.get());
						tabData.accept(ModItems.CLEANER_SPAWN_EGG.get());
						tabData.accept(ModItems.ARMY_IN_BLACK_SPAWN_EGG.get());
						tabData.accept(ModItems.CRUMBLING_ARMOR_SPAWN_EGG.get());
						tabData.accept(ModItems.THE_LADY_FACING_THE_WALL_SPAWN_EGG.get());
						tabData.accept(ModItems.LETICIA_SPAWN_EGG.get());
						tabData.accept(ModItems.SHELL_SEA_RUNNER_SPAWN_EGG.get());
						tabData.accept(ModItems.DEEPSEA_SLIDER_SPAWN_EGG.get());
						tabData.accept(ModItems.RIDGESEA_SPITTER_SPAWN_EGG.get());
						tabData.accept(ModItems.PRIMALSEA_PIERCER_SPAWN_EGG.get());
						tabData.accept(ModItems.NUCLEIC_MALEFICENT_SPAWN_EGG.get());
						tabData.accept(ModItems.BASINSEA_REAPER_SPAWN_EGG.get());
						tabData.accept(ModItems.NOTHING_THERE_SPAWN_EGG.get());
					})
					.build());

	public static final RegistryObject<CreativeModeTab> TAB_LOBOTOCRAFT_CORE = REGISTRY.register("tablobotocraft_core",
			() -> CreativeModeTab.builder().title(Component.translatable("itemGroup.lobotocraft_core")).icon(() -> new ItemStack(ModItems.ICON.get())).displayItems((parameters, tabData) -> {
						tabData.accept(ModItems.PE_BOX.get());
						tabData.accept(ModItems.CONVEYER.get());
						tabData.accept(ModItems.REGENERATION_REACTOR.get());
						tabData.accept(ModItems.ARMOR_LOCK.get());
						tabData.accept(ModItems.SPECIAL_RECORD.get());
						tabData.accept(ModItems.TARGET_MARKER.get());
						tabData.accept(ModItems.WORK_DEVICE.get());
						tabData.accept(ModItems.STRANGE_BADGE.get());
						tabData.accept(ModItems.OTTO.get());
						tabData.accept(ModItems.ESCAPE.get());
						tabData.accept(ModItems.ELEVATOR.get());
						tabData.accept(ModItems.PUNISHING_BIRD_BLOCK.get());
						tabData.accept(ModItems.TT2.get());
						tabData.accept(ModItems.CAPTURE_UNIT.get());
					})
					.build());

	public static final RegistryObject<CreativeModeTab> TAB_LOBOTOCRAFT_SUIT = REGISTRY.register("tablobotocraft_suit",
			() -> CreativeModeTab.builder().title(Component.translatable("itemGroup.lobotocraft_suit")).icon(() -> new ItemStack(ModItems.REPENTANCE_CHESTPLATE.get())).displayItems((parameters, tabData) -> {
						tabData.accept(ModItems.REPENTANCE_CHESTPLATE.get());
						tabData.accept(ModItems.REPENTANCE_LEGGINGS.get());
						tabData.accept(ModItems.REPENTANCE_BOOTS.get());
						tabData.accept(ModItems.REPENTANCE_WEAPON.get());
						tabData.accept(ModItems.REPENTANCE_CURIO.get());
						tabData.accept(ModItems.BLUE_STAR_CHESTPLATE.get());
						tabData.accept(ModItems.BLUE_STAR_LEGGINGS.get());
						tabData.accept(ModItems.BLUE_STAR_BOOTS.get());
						tabData.accept(ModItems.BLUE_STAR_WEAPON.get());
						tabData.accept(ModItems.BLUE_STAR_CURIO.get());
						tabData.accept(ModItems.CHILDREN_GALAXY_CHESTPLATE.get());
						tabData.accept(ModItems.CHILDREN_GALAXY_LEGGINGS.get());
						tabData.accept(ModItems.CHILDREN_GALAXY_BOOTS.get());
						tabData.accept(ModItems.CHILDREN_GALAXY_WEAPON.get());
						tabData.accept(ModItems.CHILDREN_GALAXY_CURIO.get());
						tabData.accept(ModItems.LARGEBIRD_CHESTPLATE.get());
						tabData.accept(ModItems.LARGEBIRD_LEGGINGS.get());
						tabData.accept(ModItems.LARGEBIRD_BOOTS.get());
						tabData.accept(ModItems.LARGEBIRD_CURIO.get());
						tabData.accept(ModItems.LARGEBIRD_WEAPON.get());
						tabData.accept(ModItems.PUNISHING_BIRD_CHESTPLATE.get());
						tabData.accept(ModItems.PUNISHING_BIRD_LEGGINGS.get());
						tabData.accept(ModItems.PUNISHING_BIRD_BOOTS.get());
						tabData.accept(ModItems.PUNISHING_BIRD_WEAPON.get());
						tabData.accept(ModItems.PUNISHING_BIRD_CURIO.get());
						tabData.accept(ModItems.APPROVAL_BIRD_CHESTPLATE.get());
						tabData.accept(ModItems.APPROVAL_BIRD_LEGGINGS.get());
						tabData.accept(ModItems.APPROVAL_BIRD_BOOTS.get());
						tabData.accept(ModItems.APPROVAL_BIRD_WEAPON.get());
						tabData.accept(ModItems.APPROVAL_BIRD_CURIO.get());
						tabData.accept(ModItems.FOURTH_MATCH_FLAME_CHESTPLATE.get());
						tabData.accept(ModItems.FOURTH_MATCH_FLAME_LEGGINGS.get());
						tabData.accept(ModItems.FOURTH_MATCH_FLAME_BOOTS.get());
						tabData.accept(ModItems.FOURTH_MATCH_FLAME_WEAPON.get());
						tabData.accept(ModItems.FOURTH_MATCH_FLAME_CURIO.get());
						tabData.accept(ModItems.WINGBEAT_CHESTPLATE.get());
						tabData.accept(ModItems.WINGBEAT_LEGGINGS.get());
						tabData.accept(ModItems.WINGBEAT_BOOTS.get());
						tabData.accept(ModItems.WINGBEAT_WEAPON.get());
						tabData.accept(ModItems.WINGBEAT_CURIO.get());
						tabData.accept(ModItems.ABANDONED_MURDERER_CHESTPLATE.get());
						tabData.accept(ModItems.ABANDONED_MURDERER_LEGGINGS.get());
						tabData.accept(ModItems.ABANDONED_MURDERER_BOOTS.get());
						tabData.accept(ModItems.ABANDONED_MURDERER_WEAPON.get());
						tabData.accept(ModItems.ABANDONED_MURDERER_CURIO.get());
						tabData.accept(ModItems.THORN_BUS_CHESTPLATE.get());
						tabData.accept(ModItems.THORN_BUS_LEGGINGS.get());
						tabData.accept(ModItems.THORN_BUS_BOOTS.get());
						tabData.accept(ModItems.THORN_BUS_WEAPON.get());
						tabData.accept(ModItems.THORN_BUS_CURIO.get());
						tabData.accept(ModItems.END_BIRD_CHESTPLATE.get());
						tabData.accept(ModItems.END_BIRD_LEGGINGS.get());
						tabData.accept(ModItems.END_BIRD_BOOTS.get());
						tabData.accept(ModItems.END_BIRD_WEAPON.get());
						tabData.accept(ModItems.END_BIRD_CURIO.get());
						tabData.accept(ModItems.PPODAE_CHESTPLATE.get());
						tabData.accept(ModItems.PPODAE_LEGGINGS.get());
						tabData.accept(ModItems.PPODAE_BOOTS.get());
						tabData.accept(ModItems.PPODAE_WEAPON.get());
						tabData.accept(ModItems.PPODAE_CURIO.get());
						tabData.accept(ModItems.FRAGMENT_OF_THE_UNIVERSE_CHESTPLATE.get());
						tabData.accept(ModItems.FRAGMENT_OF_THE_UNIVERSE_LEGGINGS.get());
						tabData.accept(ModItems.FRAGMENT_OF_THE_UNIVERSE_BOOTS.get());
						tabData.accept(ModItems.FRAGMENT_OF_THE_UNIVERSE_WEAPON.get());
						tabData.accept(ModItems.FRAGMENT_OF_THE_UNIVERSE_CURIO.get());
						tabData.accept(ModItems.SNOWQUEEN_CHESTPLATE.get());
						tabData.accept(ModItems.SNOWQUEEN_LEGGINGS.get());
						tabData.accept(ModItems.SNOWQUEEN_BOOTS.get());
						tabData.accept(ModItems.SNOWQUEEN_WEAPON.get());
						tabData.accept(ModItems.SNOWQUEEN_CURIO.get());
						tabData.accept(ModItems.CRUMBLING_ARMOR_CHESTPLATE.get());
						tabData.accept(ModItems.CRUMBLING_ARMOR_LEGGINGS.get());
						tabData.accept(ModItems.CRUMBLING_ARMOR_BOOTS.get());
						tabData.accept(ModItems.CRUMBLING_ARMOR_WEAPON.get());
						tabData.accept(ModItems.FOOLHARDY_COURAGE_CURIO.get());
						tabData.accept(ModItems.INNER_COURAGE_CURIO.get());
						tabData.accept(ModItems.RED_SHOES_CHESTPLATE.get());
						tabData.accept(ModItems.RED_SHOES_LEGGINGS.get());
						tabData.accept(ModItems.RED_SHOES_BOOTS.get());
						tabData.accept(ModItems.RED_SHOES_WEAPON.get());
						tabData.accept(ModItems.RED_SHOES_CURIO.get());
						tabData.accept(ModItems.QUEEN_BEE_CHESTPLATE.get());
						tabData.accept(ModItems.QUEEN_BEE_LEGGINGS.get());
						tabData.accept(ModItems.QUEEN_BEE_BOOTS.get());
						tabData.accept(ModItems.QUEEN_BEE_WEAPON.get());
						tabData.accept(ModItems.QUEEN_BEE_CURIO.get());
						tabData.accept(ModItems.THE_LADY_FACING_THE_WALL_CHESTPLATE.get());
						tabData.accept(ModItems.THE_LADY_FACING_THE_WALL_LEGGINGS.get());
						tabData.accept(ModItems.THE_LADY_FACING_THE_WALL_BOOTS.get());
						tabData.accept(ModItems.THE_LADY_FACING_THE_WALL_WEAPON.get());
						tabData.accept(ModItems.THE_LADY_FACING_THE_WALL_CURIO.get());
						tabData.accept(ModItems.HAPPY_TEDDY_CHESTPLATE.get());
						tabData.accept(ModItems.HAPPY_TEDDY_LEGGINGS.get());
						tabData.accept(ModItems.HAPPY_TEDDY_BOOTS.get());
						tabData.accept(ModItems.HAPPY_TEDDY_WEAPON.get());
						tabData.accept(ModItems.HAPPY_TEDDY_CURIO.get());
						tabData.accept(ModItems.LETICIA_CHESTPLATE.get());
						tabData.accept(ModItems.LETICIA_LEGGINGS.get());
						tabData.accept(ModItems.LETICIA_BOOTS.get());
						tabData.accept(ModItems.LETICIA_WEAPON.get());
						tabData.accept(ModItems.LETICIA_CURIO.get());
						tabData.accept(ModItems.HELPER_CHESTPLATE.get());
						tabData.accept(ModItems.HELPER_LEGGINGS.get());
						tabData.accept(ModItems.HELPER_BOOTS.get());
						tabData.accept(ModItems.HELPER_WEAPON.get());
						tabData.accept(ModItems.HELPER_CURIO.get());
						tabData.accept(ModItems.BUTTERFLY_FUNERAL_CHESTPLATE.get());
						tabData.accept(ModItems.BUTTERFLY_FUNERAL_LEGGINGS.get());
						tabData.accept(ModItems.BUTTERFLY_FUNERAL_BOOTS.get());
						tabData.accept(ButterflyFuneralWeapon.createWhiteWeapon(ModItems.BUTTERFLY_FUNERAL_WEAPON.get()));
						tabData.accept(ButterflyFuneralWeapon.createBlackWeapon(ModItems.BUTTERFLY_FUNERAL_WEAPON.get()));
						tabData.accept(ModItems.BUTTERFLY_FUNERAL_CURIO.get());
						tabData.accept(ModItems.BIG_BADWOLF_CHESTPLATE.get());
						tabData.accept(ModItems.BIG_BADWOLF_LEGGINGS.get());
						tabData.accept(ModItems.BIG_BADWOLF_BOOTS.get());
						tabData.accept(ModItems.BIG_BADWOLF_WEAPON.get());
						tabData.accept(ModItems.BIG_BADWOLF_CURIO.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_CHESTPLATE.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_LEGGINGS.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_BOOTS.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_WEAPON_KNIFE.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_WEAPON_GUN.get());
						tabData.accept(ModItems.REDHAT_MERCENARY_CURIO.get());
						tabData.accept(ModItems.SHEEPSKIN_CURIO.get());
					})
					.build());

	public static final RegistryObject<CreativeModeTab> TAB_LOBOTOCRAFT_DEBUG = REGISTRY.register("tablobotocraft_debug",
			() -> CreativeModeTab.builder().title(Component.translatable("itemGroup.lobotocraft_debug")).icon(() -> new ItemStack(ModItems.STRUCTURE_TOOL_SAFE.get())).displayItems((parameters, tabData) -> {
						tabData.accept(ModItems.STRUCTURE_TOOL_SAFE.get());
						tabData.accept(ModItems.REMOVER.get());
						tabData.accept(ModItems.ENTITY_ESCAPE.get());
						tabData.accept(ModItems.STOP_ESCAPE.get());
						tabData.accept(ModItems.ICON.get());
					})
					.build());
}
